Package.Require("./NACT_Behavior.lua")
Package.Require("./Idle.lua")
Package.Require("./Detection.lua")
Package.Require("./Engage.lua")
Package.Require("./Cover.lua")
Package.Require("./Patrol.lua")
Package.Require("./Combat.lua")