name: "Update documentation"
on: 
  push:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/checkout@v4
        name: "Clone NACT"
        with:
          path: 'nact'
      - name: Install LuaLS
        run: |
          wget https://github.com/LuaLS/lua-language-server/releases/download/3.13.6/lua-language-server-3.13.6-linux-x64.tar.gz
          tar -xvf lua-language-server-3.13.6-linux-x64.tar.gz
          ls -la
          mkdir doc_result
      - name: Run LuaLS docgen
        run: |
          ./bin/lua-language-server --doc ./nact --doc_out_path ./doc_result
          cat ./doc_result/doc.json
          mkdir ./doc_markdown
      - name: Generate markdown from json
        run: |
          node ./nact/.github/scripts/docgen.js ./doc_result/doc.json ./doc_markdown
          ls -la ./doc_markdown